### ISSUE TITLE
React Konva doesn't work with React 16.3 Context API

### ISSUE THREAD

**Issue by Guria** [konvajs/react-konva#188] opened 2018-04-07 10:40 UTC
I am trying to use React 16.3 Context API based on render props with React Konva:
```js
import React from "react";
import { Layer, Stage, Circle, Group, Line } from "react-konva";

const { Consumer, Provider } = React.createContext({ width: 0, height: 0 });

const ToolsLayer = () => (
  <Consumer>
    {({ height, width }) => (
      <Layer>
        <Group offsetY={-height} y={-42}>
          <Line
            points={[0, 0, width, 0, width, 42, 0, 42]}
            closed
            stroke="black"
          />
          <Circle radius={11} fill="red" stroke="black" x={21} y={21} />
          <Circle radius={11} fill="green" stroke="black" x={21 + 42} y={21} />
          <Group />
        </Group>
      </Layer>
    )}
  </Consumer>
);

export default function Canvas({
  width = window.innerWidth,
  height = window.innerHeight
}) {
  return (
    <Provider value={{ width, height }}>
      <Stage width={width} height={height}>
        <ToolsLayer />
      </Stage>
    </Provider>
  );
}
```
And I get runtime error:
```
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

Check the render method of `ToolsLayer`.
```
Reproducible demo: https://codesandbox.io/s/2o9j1r6l30

**Comment by jeremypenner** [comment] 2018-05-12 14:46
This is still broken on v1.7.2. You can see in the reproducible demo linked above that it's picking up the default value defined by the initial creation of the context (`{width: 0, height: 0}`) rather than the values provided by Provider.

**Comment by lavrton** [comment] 2018-05-14 02:28
Tracking here: https://github.com/facebook/react/issues/12796

**Comment by gaearon** [comment] 2018-08-07 01:31
https://github.com/facebook/react/issues/13336

**Comment by lyleunderwood** [comment] 2018-08-21 15:11
[Here's](https://github.com/facebook/react/issues/13336#issuecomment-414709155) an example of a quick workaround I put together to try and sort of contain this.

**Comment by Guria** [comment] 2018-09-28 14:55
Any updates here?

**Comment by gaearon** [comment] 2018-09-28 15:10
Usually when there are updates on an issue, they happen on the issue itself. :-)

But since you're asking, https://github.com/facebook/react/pull/13728 will likely help. It will be in the next React release. That would help you "bridge" the context you care about down.

**Comment by gaearon** [comment] 2018-09-28 15:28
Yea

**Comment by ZikDead** [comment] 2018-12-28 20:07
Is the way to make it work with react-konva? My consumer returns default value of context

**Comment by drcmda** [comment] 2019-02-28 12:27
Maybe allowing for something like this:

```jsx
// Takes a context from a foreign render-reconciler, subscribes to it, which consumes it in the root component
// Then returns the context provider which belongs to this reconciler tree so that it can be consumed properly
function useParentContent(context) {
  const ref = useRef()
  const { subscribeContext, context } = useContext(context)
  const { unsub, wrappedContext } = useMemo(() => subscribeContext(context, ref), [context])
  useEffect(() => unsub, [context])
  return useContext(wrappedContext)
}
```

Which would basically transport context into the reconciler tree.

**Comment by lavrton** [comment] 2019-03-31 00:54
Demo how to "bridge" contexts into `react-konva` tree:

```javascript
import React, { Component } from "react";
import Konva from "konva";
import { render } from "react-dom";
import { Stage, Layer, Rect } from "react-konva";

const ThemeContext = React.createContext("red");

const ThemedRect = () => {
  const value = React.useContext(ThemeContext);
  return (
    <Rect x={20} y={50} width={100} height={100} fill={value} shadowBlur={10} />
  );
};

const Canvas = () => {
  return (
    <ThemeContext.Consumer>
      {value => (
        <Stage width={window.innerWidth} height={window.innerHeight}>
          <ThemeContext.Provider value={value}>
            <Layer>
              <ThemedRect />
            </Layer>
          </ThemeContext.Provider>
        </Stage>
      )}
    </ThemeContext.Consumer>
  );
};

class App extends Component {
  render() {
    return (
      <ThemeContext.Provider value="blue">
        <Canvas />
      </ThemeContext.Provider>
    );
  }
}

render(<App />, document.getElementById("root"));
```

https://codesandbox.io/s/ykqw8r4r21

**Comment by lavrton** [comment] 2019-09-30 16:11
I am going to close the issue. I don't think we can do anything from our side to resolve the issue and handle context bridging automatically.

**Closed by lavrton** 2019-09-30 16:11 UTC

**Comment by harryhle** [comment] 2019-12-06 20:59
I encountered this issue with my project. After playing with it, I realize that we can skip the bridge by declaring the context consumer inside `Stage`. So something like this will work just fine.

```
import React, { Component } from "react";
import { render } from "react-dom";
import { Stage, Layer, Rect } from "react-konva";

const ThemeContext = React.createContext();

const ThemedRect = () => {
  const value = React.useContext(ThemeContext);
  return (
    <Rect x={20} y={50} width={100} height={100} fill={value} shadowBlur={10} />
  );
};

const Canvas = () =>  (
  <Stage width={window.innerWidth} height={window.innerHeight}>
    <ThemeContext.Provider value="blue">
      <Layer>
        <ThemedRect />
      </Layer>
    </ThemeContext.Provider>
  </Stage>
)

class App extends Component {
  render() {
    return <Canvas />
  }
}

render(<App />, document.getElementById("root"));

```
https://codesandbox.io/s/react-konva-consume-context-demo-d5yht

**Comment by lyleunderwood** [comment] 2019-12-06 21:36
@harryhle That seems unrelated as you're not actually bridging the gap between the two renderers there, both the provider and the consumer are on the `react-konva` side of the bridge, and therefore no bridging is necessary.

**Comment by harryhle** [comment] 2019-12-06 22:22
@lyleunderwood That's right. I actually work around this problem by passing data between two renderers by transferring `props`, instead of using the second context as bridge.

**Comment by dylinmaust** [comment] 2021-08-31 20:23
Is there a way to bridge react-query's `QueryClientProvider` or Material UIs `MuiThemeProvider` using this same technique?

**Comment by lyleunderwood** [comment] 2021-08-31 21:31
`react-query` doesn't seem to expose a consumer directly. You could probably do something like:

```javascript
import { useQueryClient, QueryClientProvider } from 'react-query';

const Canvas = () => {
  const queryClient = useQueryClient();

  return (
    <QueryClientProvider client={queryClient}>
        <Stage />
    </QueryClientProvider>
  );
};
```

**Comment by lyleunderwood** [comment] 2021-08-31 21:38
Similarly for MUI we should be able to do something like:

```javascript
import { ThemeProvider, useTheme } from '@material-ui/core/styles';

const Canvas = () => {
  const theme = useTheme();

  return (
    <ThemeProvider theme={theme}>
      <Stage />
    </ThemeProvider>
  );
};
```

**Comment by dylinmaust** [comment] 2021-09-01 14:16
@lyleunderwood Thanks! I actually had implemented it in such a way for the `<Stage>`, but was also using the `<Html>` component from react-konva-utils, which requires a second bridge. So I mistakenly thought it wasn't bridging correctly.

**Comment by maritaria** [comment] 2022-06-12 11:18
The usage of context api should probably be an example on the offical docs site, there is no mention there of this problem/pitfall and I only found this due to some google searches (which first led me in other directions).

**Comment by lavrton** [comment] 2022-09-23 14:56
Update on this issue. From `react-konva@18.2.2`, context bridge should work by default. It will be really cool if someone can try it and provide feedback.

**Comment by Nimbo1999** [comment] 2022-09-23 17:07
I've just tested the new version and the context bridge its working fine on my case 👍

**Comment by bekirisgor** [comment] 2022-10-03 00:40
Thanks for the update that works now :)

**Comment by Lucas1Chaves** [comment] 2022-10-10 03:27
I started to get a new error on version 18.2.2 
![image](https://user-images.githubusercontent.com/27892674/194795210-fc906e93-0190-416d-835b-024c4836f66b.png)

On 18.2.1 it worked even without Bridge component, i'm declaring recoil root on top of the component tree of my app instead of inside stage.

**Comment by lavrton** [comment] 2022-10-10 16:06
Can you make a demo?
