### ISSUE TITLE
polygon showing curved line only in firefox

### ISSUE THREAD

**Issue by mdmusaib** [konvajs/react-konva#507] opened 2020-08-10 07:44 UTC
I'm using custom react shape component for drawing polygon, 
passing points array while drawing polgon...
 <Shape
          sceneFunc={(context, shape) => {
            context.beginPath();
            props.points && props.points.map((data, i) => context.lineTo(data?.x - startX, data?.y - startY));
            props.isClosed && context.closePath();
            // context._applyLineCap('miter');
            context.fillStrokeShape(shape);
          }}
/>

issue is polygon getting curved line on closing of polygon only in firefox browser.. here i'm sharing the pics of both chrome and firefox
**In chrome**
<img width="439" alt="chrome_pic" src="https://user-images.githubusercontent.com/19144712/89761114-6131d380-db0b-11ea-9824-0f01c2cda774.png">

**IN firefox** 
<img width="554" alt="firefox_pic" src="https://user-images.githubusercontent.com/19144712/89761131-68f17800-db0b-11ea-91cd-6dc62c5d7688.png">

we have tried using lineJoin, lineCap in shape, but it is not working in firefox browser.

**Comment by lavrton** [comment] 2020-08-10 13:53
Can you make a small full demo?

**Comment by mdmusaib** [comment] 2020-08-10 15:03
here i make a small demo of the above issue, https://jebeq.csb.app/

**Comment by lavrton** [comment] 2020-08-10 21:49
I don't see any differences. I see just this everywhere:
<img width="284" alt="Screen Shot 2020-08-10 at 16 48 40" src="https://user-images.githubusercontent.com/1443320/89834948-63a32600-db29-11ea-90bd-cb02c8816452.png">

**Comment by mdmusaib** [comment] 2020-08-11 00:28
May be because of browser update, my Firefox version is may be low? Can you send me ur firefox version, so that I can update the same

**Comment by lavrton** [comment] 2020-08-11 17:03
I have the same version on Mac. But my picture is different from what you attached to the first post.

**Comment by mdmusaib** [comment] 2020-08-12 00:50
I'm using Windows Operating system, may be because of the operating system problem, can you tell me any solution on that.

**Comment by lavrton** [comment] 2020-08-12 19:21
Try to make a smaller demo with plain canvas API, without Konva and react. So if the issue is coming from `konva` or `react-konva` - we may try to fix it.

**Comment by mdmusaib** [comment] 2020-08-13 09:34
I have made a smaller demo for your reference 
https://oh20g.csb.app/

<img width="941" alt="Annotation 2020-08-13 150226" src="https://user-images.githubusercontent.com/19144712/90118549-08b23e80-dd76-11ea-9c6c-eaadc3d3bd5f.png">

In firefox also it is showing same using javascript canvas, I think it is a firefox issue, I'm using windows operating system, 
how to solve this, whether we need to raise issue in firefox or any solutions...

**Comment by lavrton** [comment] 2020-08-13 14:56
> whether we need to raise the issue in firefox or any solutions

Yes, you should go to the Firefox bugs tracker. I am going to close the issue because it is not `konva` related.

**Closed by lavrton** 2020-08-13 14:56 UTC
