### ISSUE TITLE
Text wrapping goes wrong if ellipsis=true

### ISSUE THREAD

**Issue by ocooper** [konvajs/react-konva#707] opened 2022-08-02 13:29 UTC
When given fixed width and long text, Konva will wrap the text on multiple lines.
If the element has the ellipsis flag, Konva adds ellipsis on every line, even if wrapping mid-word.
Also, sometimes Konva will deduce it doesn't have enough space even though it has. The cause of that is the the ellipsis is assumed to be on every line. See line 432 in Text.ts
Reproduction of the bug here: [code sandbox](https://codesandbox.io/s/text-width-forked-yggowj)

**Comment by lavrton** [comment] 2022-08-02 15:28
I don't see reproduction on that link.

**Comment by ocooper** [comment] 2022-08-03 06:25
Sorry, the link is bad (first time using codesandbox)
I tried making another sandbox [here](https://codesandbox.io/s/text-width-forked-1ojh75?file=/src/index.js).

**Comment by lavrton** [comment] 2022-08-05 15:11
It looks like it is fixed with on the last Konva version. 

I updated all dependencies and it works good: https://codesandbox.io/s/text-width-forked-q3pu9v?file=/src/index.js

**Closed by lavrton** 2022-08-05 15:11 UTC
