### ISSUE TITLE
opacity property in <Rect/> occur error

### ISSUE THREAD

**Issue by tae100k** [konvajs/react-konva#698] opened 2022-07-04 06:17 UTC
- Hello, I'm using your React-Konva library and find it super easy and helpful!
- I just have 1 issue atm. everything worked fine until I add `opacity={opacity}` on Rect component.
- I also tried `opacity="0.8"`(which caused type error) and `opacity={0.8}` but it also caused exact same error. So I'm wondering is this my problem or konva opacity problem!
- I'd appreciate if you also let me know what I could do to fix it!
-  FYL) `rgba()` worked fine to add opacity! But I'm asking just in case I'm missng something about opacity propery or any possible issues 

Thanks a lot!

[Error]
![스크린샷 2022-07-04 오후 3 11 07](https://user-images.githubusercontent.com/78027252/177092274-61378867-119a-4fc6-8c36-0a37b1f674ee.png)

[My Code]
```
const VerticallyDraggableDiv: React.FC<VerticallyDraggableDivProps> = ({
  x,
  y,
  width,
  height,
  handleDragging,
  handleDragEnd,
  borderColor,
  backgroundColor,
  text,
  fontColor,
  idx,
}) => {
  const [opacity, setOpacity] = useState(0.5);
  return (
    <Group
      x={x}
      y={y}
      draggable
      dragBoundFunc={(pos) => handleDragging({ pos })}
      onDragEnd={idx !== undefined && handleDragEnd ? (e) => handleDragEnd({ e, idx }) : undefined}
    >
      <Rect
        width={width}
        height={height}
        stroke={borderColor}
        strokeWidth={0.3}
        fill={backgroundColor}
        text={text}
        cornerRadius={2}
        opacity={opacity} // opacity is here!
      />
      <Text
        width={width}
        height={height}
        fill={fontColor}
        fontSize={20}
        align="center"
        verticalAlign="middle"
        text={text}
      />
    </Group>
  );
};

export default VerticallyDraggableDiv;
```

+Also my react-konva and konva versions are like below
```
    "konva": "^8.3.6",
    "react-konva": "^17.0.2-6",`
```

**Comment by lavrton** [comment] 2022-07-04 17:48
Can you make a demo?

**Comment by tae100k** [comment] 2022-07-05 01:40
Yes, for sure.
As you can see, as soon as I add that opacity property, it makes a error.


https://user-images.githubusercontent.com/78027252/177232992-fc6e6f6b-0dee-4f61-9938-98a0c7a240b1.mov

**Comment by tae100k** [comment] 2022-07-06 05:17
@lavrton I'd like to know is it just Konva's internal bug! So in that case, I just can use rgba() instead.

**Comment by lavrton** [comment] 2022-07-06 13:57
I need online demo with the code, so I can reproduce it.

**Comment by tae100k** [comment] 2022-07-08 04:46
@lavrton 
I indeed understand that you need online demo with the code. I'm real sry to say this but I can't because this code is belonged to the company's project that hasn't released yet.
So in this case, could I know the possible reason why "Failed to execute" happens in Konva when there's no image?
I'm rlly sorry that I can't share the online demo again.

**Comment by lavrton** [comment] 2022-07-12 15:23
I don't know. This is why I need a demo. You don't need to give access to your app or copy its code. Just make a small, reproducible demo. Simple stage with one rectangle. And set properties in a way when error is visible.

**Comment by blinz117** [comment] 2022-11-07 15:56
I've also been experiencing this.

My use case is that I'm setting the size of my stage with values provided by the `useMeasure` hook from the [`react-use` library](https://streamich.github.io/react-use/?path=/story/sensors-usemeasure--docs). I'm using it to fit the stage to the space available to it to account for other non-Konva React components that take up space as well - i.e. I don't necessarily want to use the whole size of the window for the Konva stage.

With the hook though, the width and height are initially both 0, I guess while the "real" size is being determined. Given that I don't use opacity, the size eventually resolves correctly and things work fine.

However, if I enable opacity while using both fill and stroke and the size is initially zero, then I get the same error.

Here is a [demo on stackblitz](https://stackblitz.com/edit/react-ts-gnwgxv?file=App.tsx) that demonstrates this. Uncomment the opacity line and refresh the preview page to see the error.

**Comment by lavrton** [comment] 2022-11-17 03:59
Looks like Konva can't handle the case, when size of the stage is 0. As a workaround, set minimum to 1.

```js
const [ref, { width, height }] = useMeasure();
<Stage width={Math.max(1, width)} height={Math.max(1, height)}>
```


Closing, as extreme edge case. But I am happy to apply Pull Request to handle zero stage size correctly.

**Closed by lavrton** 2022-11-17 03:59 UTC
