### ISSUE TITLE
Incompatibility of react-konva and konva libs

### ISSUE THREAD

**Issue by nikolai-shilin** [konvajs/react-konva#714] opened 2022-10-14 11:28 UTC
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/s/Developer/grade/node_modules/konva/lib/Core.js from /Users/s/Developer/grade/node_modules/react-konva/lib/ReactKonvaCore.js not supported.
Instead change the require of Core.js in /Users/s/Developer/grade/node_modules/react-konva/lib/ReactKonvaCore.js to a dynamic import() which is available in all CommonJS modules.

node version 18.10.0
Should I degrade konva version to make it work?

**Comment by lavrton** [comment] 2022-11-17 03:19
Do you use some js bundlers? Or is it jest?

**Comment by luco** [comment] 2023-01-31 13:29
Getting this as well. Using `next@12.1.0`.

**Comment by xstolar** [comment] 2023-02-09 16:49
> Getting this as well. Using `next@12.1.0`.

same here next@12.2.2

**Comment by jorgeluis11** [comment] 2023-03-01 18:14
Same next@13.2.1

**Comment by jorgeluis11** [comment] 2023-03-01 18:29
Hello everybody,

Check Komarnisky comment #655.

1. Just move everything that import Konva to a component.
2. Then Import the component dynamically, seems to be working for me.

Example:

Definition:
```
import React from 'react';
import { Stage } from 'react-konva';

const TeamTrendsBarChart = () => {
  return <Stage width={200} height={100} />;
};
```
export default TeamTrendsBarChart;
```
Usage:
```
const TeamTrendsBarChart = dynamic(
  () => import('../../Team/components/TeamTrendsBarChart'),
  { ssr: false }
);

export const Page = () => {
  return <TeamTrendsBarChart />;
}
```

**Comment by m4rtinpf** [comment] 2023-04-13 01:52
I'm getting the same error. I am **NOT** using Next, but vite+vitest+react-testing-library.

Repo to reproduce: https://github.com/m4rtinpf/react-konva-vitest

Downgrading node from 18 to 16 makes no difference.

The fix from the [comment](https://github.com/konvajs/react-konva/issues/714#issuecomment-1450653086) above doesn't work either.

Long shot, not my forte: Could this be related to `react-konva` being [released with node 6.11](https://github.com/konvajs/react-konva/blob/master/.travis.yml#L3)?

**Comment by lavrton** [comment] 2023-04-13 22:30
> Konva has no node with the type Rect. Group will be used instead. 

This one is very strange. It should fully load Konva. It looks like it is loaded twice with different version (cmj vs es). Need to find why.

**Comment by m4rtinpf** [comment] 2023-04-13 22:42
> > Konva has no node with the type Rect. Group will be used instead.
> 
> This one is very strange. It should fully load Konva. It looks like it is loaded twice with different version (cmj vs es). Need to find why.

[One of the tests](https://github.com/konvajs/react-konva/blob/master/test/react-konva-test.tsx#L512) of `react-konva` is giving the same error (on `master`):

>  Test Events  
>    ✅ should remove events on unmount  
>  Bad structure  
>Konva has no node with the type div. Group will be used instead. If you use minimal version of react-konva, just import required nodes into Konva: "import "konva/lib/shapes/div"  If you want to render DOM elements as part of canvas tree take a look into this demo: https://konvajs.github.io/docs/react/DOM_Portal.html

**Comment by lavrton** [comment] 2023-04-13 22:45
This one is expected. `Rect` shape must be defined in your tests. I am afraid there is something much deeper in the issue. Probably we need some fixes from `konva` side too.

**Comment by m4rtinpf** [comment] 2023-04-13 22:52
I [imported](https://github.com/m4rtinpf/react-konva-vitest/commit/9f79bece4b8e4048ba8f3cb7267fdf518cc87729) `Rect` on the test file and the error keeps showing.

But it's okay, I don't plan to actually _test_ the canvas with `react-testing-library`, I just wanted to be able to _run the tests_ when a canvas element was on the page.

**Comment by lavrton** [comment] 2023-04-14 16:10
I made a fix from konva side. `npm install konva@latest`. It should work correctly now. Please confirm.

**Closed by lavrton** 2023-04-14 16:10 UTC

**Comment by m4rtinpf** [comment] 2023-04-14 16:45
[Confirmed working](https://github.com/m4rtinpf/react-konva-vitest/commit/fc22db3440c73834d42e572c6d5c89831a56f414):

```
$ npm run test

> react-konva-vitest@0.0.0 test
> vitest run src


 RUN  v0.30.1 /home/paul/work/react-konva-vitest

 ✓ src/__tests__/App.test.tsx (1)

 Test Files  1 passed (1)
      Tests  1 passed (1)
   Start at  13:42:28
   Duration  768ms (transform 35ms, setup 0ms, collect 151ms, tests 51ms, environment 202ms, prepare 55ms)
```

It overrides a peer dependency though:

```
$ npm install konva@latest
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: react-konva-vitest@0.0.0
npm WARN Found: konva@8.4.3
npm WARN node_modules/konva
npm WARN   peer konva@"^8.0.1 || ^7.2.5" from react-konva@18.2.5
npm WARN   node_modules/react-konva
npm WARN     react-konva@"^18.2.5" from the root project
npm WARN   1 more (the root project)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer konva@"^8.0.1 || ^7.2.5" from react-konva@18.2.5
npm WARN node_modules/react-konva
npm WARN   react-konva@"^18.2.5" from the root project
```

Closing #744 

Thanks for the quick fix! :)

**Comment by lavrton** [comment] 2023-04-14 16:48
@m4rtinpf thanks for confirming. And thanks for a good repo to reproduce the issue.
