### ISSUE TITLE
Different behavior for list rendered by normal react and react-konva.

### ISSUE THREAD

**Issue by Dominionys** [konvajs/react-konva#636] opened 2021-12-14 14:25 UTC
Hi,
Thank you for your library, it's awesome!

I'm trying to understand why react-konva has different behavior with list.
I have a [test application ](https://codesandbox.io/s/adoring-burnell-nuppw)
It uses react, react-redux, react-konva. 

```
export default function App() {
  return (
    <div className="App">
      <Stage width={300} height={100}>
        <Provider store={store}>
          <Layer>
            <KonvaList />
          </Layer>
        </Provider>
      </Stage>
      <Provider store={store}>
        <DomList />
      </Provider>
    </div>
  );
}
```

### It renders list with react-konva:

```
export function KonvaList() {
  const list = useAppSelector((state) => state.list.list);
  return (
    <>
      {list.map((v) => {
        return <KonvaItem key={v.id} id={v.id} />;
      })}
    </>
  );
}
```

```
function KonvaItemComponent(props: { id: number }) {
  const dispatch = useAppDispatch();

  const storeItem = useAppSelector((state) => {
    const item = state.list.list.find((value) => value.id === props.id);
    const { id, value } = item!;
    return {
      id,
      value
    };
  });

  return (
    <Rect
      x={60 * storeItem.id}
      y={20}
      width={50}
      height={50}
      fill={"black"}
      shadowBlur={5}
      onClick={() => dispatch(remove(props))}
    />
  );
}
```

### It renders list with react:
```
export function DomList() {
  const list = useAppSelector((state) => state.list.list);
  return (
    <div>
      {list.map((v) => {
        return <DomItem id={v.id} key={v.id} />;
      })}
    </div>
  );
}
```

```
function DomItemComponent(props: { id: number }) {
  const dispatch = useAppDispatch();

  const itemStore = useAppSelector((state) => {
    const item = state.list.list.find((value) => value.id === props.id);
    const { id, value } = item!;
    return {
      id,
      value
    };
  });
  return <div onClick={() => dispatch(remove(props))}>{itemStore.id}</div>;
}
```
If we click on rectangle or on number it deletes clicked item from store. 
Problem with list which is rendered by react-konva. It has an error if we delete an item. But there is no any error with normal list.
You can comment `KonvaList` or `DomList` in `App.tsx`.

**Comment by lavrton** [comment] 2021-12-14 16:23
It looks like it is because of order of updates is not correct. The child component is updated before the parent component.

It comes from `react-redux`. I am not sure I can do anything from `react-konva` side.

See this for more info:
https://github.com/reduxjs/react-redux/issues/1589
https://github.com/reduxjs/react-redux/issues/1510

**Comment by Dominionys** [comment] 2021-12-14 16:47
Hmm,
If it was `react-redux` problem it would reproduce with normal react components. But if you comment `KonvaList` usage in `App.tsx` and delete item, we don't get any error.

**Comment by Dominionys** [comment] 2021-12-14 17:06
If I understand correctly child component updating before parent component is [valid case](https://github.com/reduxjs/react-redux/blob/0bcaec47338e26c5a43f8dbc2593b5d84e312281/src/hooks/useSelector.js#L82).  They catch error on store update and wait error on next [component render](https://github.com/reduxjs/react-redux/blob/0bcaec47338e26c5a43f8dbc2593b5d84e312281/src/hooks/useSelector.js#L50). 

Following action sequence:
1. Dispatch delete action.
2. Store gets new state.
3. Store starts notify current subscribers.
4. Children subscribe callback calls before parent, we catch error and wait next child render with error.
5. Parent gets update.
6. Parent unmount deleted children component.
7. Children component render, which got error on step 4, isn`t called because component was unmounted.

 But with `react-konva` it seems that we call children render on step 7.

**Comment by lavrton** [comment] 2022-04-27 14:42
Closing the issue because I am not sure what to fix here.

If it is still important for you, please make a minimal demo to reproduce the issue.

**Closed by lavrton** 2022-04-27 14:42 UTC
