### ISSUE TITLE
Handling stage dragBoundFunc on scaling

### ISSUE THREAD

**Issue by roshansachan** [konvajs/react-konva#573] opened 2021-04-20 21:22 UTC
I have used dragBoundFunc to limit a user from dragging the stage out of view. It works fine in the default state. But when I scale the stage, the bounding doesn't work for the top and left side of the stage.

        dragBoundFunc={(pos) => {
                  let newY = pos.y;
                  let newX = pos.x;
                  //limit at 10px, when user tries to take move the stage out of view
                  if (pos.y > stageResolution.height - 10) {
                    newY = stageResolution.height - 10;
                  }
                  
                  //This doesn't work on scaling. This is the rule for top boundary
                  if (pos.y < -(stageResolution.height - 10)) {
                    newY = -(stageResolution.height - 10);
                  }
                  
                  if (pos.x > stageResolution.width - 10) {
                    newX = stageResolution.width - 10;
                  }
                  
                  //This doesn't work on scaling. This is the rule for left boundry.
                  if (pos.x < -(stageResolution.width - 10)) {
                    newX = -(stageResolution.width - 10);
                  }
                  return {
                    x: newX,
                    y: newY
                  };
          }}
          
Here is a video,

https://user-images.githubusercontent.com/4952904/115464869-59eec800-a24b-11eb-9547-b2b7986ee3b1.mov

[Here is the working example. ](https://codesandbox.io/s/react-konva-basic-demo-forked-zjp5z?file=/index.js:33691-34468)

I tried multiplying the stage width and height with stage stageScale.x and stage stageScale.y respectively but even that didn't 
work.
```
if(pos.y < -(stageResolution.height*stageScale.y -10) ){
    newY = -(stageResolution.height*stageScale.y -10)
}
```

**Comment by HNOONa-0** [comment] 2021-08-24 17:56
i think you should multiply the margin (the distance you want shape away from edges of stage) by the scale not width/height of scale,
here is my handleDragBound function for a 60 * 60 square, the x, y of sqaure is top-left vertex,
this piece of code works for me although i dont understand it completely, i just played around with it for a little bit and got a more desirable result:
`outOfBoundsHandle = (pos, height = this.state.height,
        width = this.state.width, scale = this.state.scale, margin = this.state.margin) => {
        return {
            x: pos.x < margin * scale ? margin * scale :
                (pos.x + (60 + margin) * scale > width ? width - (60 + margin) * scale : pos.x),
            y: pos.y < margin * scale ? margin * scale :
                (pos.y + (60 + margin) * scale > height ? height - (60 + margin) * scale : pos.y)
        }
    }`
height->stage height
width->stage width
scale->current scale value of stage
margin->distance required to be away from edges

i dont know about your zoom in/out logic, implementation, but here is what i used, yours might be different and could end up producing different results
:https://colinwren.medium.com/adding-zoom-and-panning-to-your-react-konva-stage-3e0a38c31d38

**Comment by KamaMakh** [comment] 2022-03-16 10:21
Still no any solutions?

**Comment by lavrton** [comment] 2022-03-21 20:15
I am closing the issue, as the demo is too large. Please make a minimal demo with just required code. 

You may need to change your calculations.

Also, I recommend to use `dragmove` event instead of `dragBoundFunc()` to limit dragging. Working in local coordinates is usually simpler.

**Closed by lavrton** 2022-03-21 20:15 UTC

**Comment by jellohouse** [comment] 2022-04-18 20:58
I'm having a similar issue I think is related... 
I implemented emulated screen moving scrolling of the canvas. using method 4 here: https://konvajs.org/docs/sandbox/Canvas_Scrolling.html#How-to-display-and-scroll-a-very-big-html5-canvas

But then if I scroll the canvas a bit, the dragboundfunc((pos) => {}) position does not behave properly.. 

I think the transform of the stage (in my case to scroll & in your case to scale) returns weird positions on the dragboundfunc...

**Comment by lavrton** [comment] 2022-04-18 21:17
@jellohouse please make a minimal online demo to reproduce.

**Comment by ersathCodes** [comment] 2024-07-19 10:39
recently i am faced the same problem if anyone found the solution please share it
