### ISSUE TITLE
React konva freezes web app

### ISSUE THREAD

**Issue by Chrischuck** [konvajs/react-konva#640] opened 2022-01-20 21:54 UTC
Hello, I'm having a fairly  similar issue to #827 where react-konva just freezes up the browser. I assume it has something to do w/ webpack but I'm not really sure what it is. 

Originally we were attempting to wrap react-konva in an internal node module for our web application. Using the module in storybook works, but when using it in a real life app, it freezes. After getting this freezing issue, I tried to add react-konva directly to our app. Even after trying to mount a very simple example, it freezes:

```
 <Stage width={100} height={100}>
    <Layer>
      <Text text="Try click on rect" />
    </Layer>
  </Stage>
```

No errors in console, just the instant the component mounts, the cpu usage shoots to 100%. I've tried in both Brave and Chrome, but no errors  in each.

react-konva version: `17.0.2-5`
konva version: `8.3.0`
webpack version: `5.50.0`
react version: `17.0.2`

Some webpack plugins/loaders we're using:

- script-loader
- webpack-dev-server
- webpack-merge
- html-webpack-plugin
- webpack.ProvidePlugin
- webpack.DllReferencePlugin
- webpack.DefinePlugin
- AddAssetHtmlPlugin
- babel-loader
- webpack.HotModuleReplacementPlugin
- CaseSensitivePathsPlugin
- ExtractTextPlugin
- webpack.ContextReplacementPlugin
- webpack.ProvidePlugin

I know it's kind of a long shot and I unfortunately don't have much info to give you, but you have any ideas of what might conflict w/ react-konva, that would be great.

Thanks for the help, it's much appreciated!

**Comment by lavrton** [comment] 2022-01-20 22:26
When you have a freeze, try to pause scripts execution in Dev Tools. Probably you will see who took the resources.

**Comment by Juliazlj** [comment] 2022-01-25 08:06
Yes, I have the same problem.

**Comment by ShayanJavadi** [comment] 2022-02-16 01:45
Getting this exact same issue happening. @Chrischuck did you ever solve the issue? I've been stuck fixing it for a few weeks now. @lavrton any assistance with this would be appreciated.

**Comment by cloudtaxi** [comment] 2022-03-17 09:11
Got memory leak with the latest version(`^17.0.2-5`) . 
![photo_2022-03-16_16-41-58](https://user-images.githubusercontent.com/16660768/158775912-1f161798-900b-4200-bb99-39f6bc89c508.jpg)

the Old one(`^16.8.6`) works without issues.
![photo_2022-03-16_16-36-43](https://user-images.githubusercontent.com/16660768/158775924-f5c1e1c7-f8d9-4e3c-9371-7b97c71af836.jpg)

**Comment by lavrton** [comment] 2022-04-27 14:43
Closing because I can't reproduce it. If you still have the problem, please make a demo.

**Closed by lavrton** 2022-04-27 14:43 UTC
