### ISSUE TITLE
I need a polygon editor capability

### ISSUE THREAD

**Issue by davesargrad** [konvajs/react-konva#720] opened 2022-12-13 15:24 UTC
I want to be able to edit a polygon:

- Insert points
- Delete points
- Drag points
- Drag polygon

Do you have this capability in a simple example? Can you please point me to an example.

The best I've found is this snippet on codepen.
https://codepen.io/akitanak/pen/wEMQvL

This snippet is doing  "news" to construct objects such as the Line object.  I never fully understand how to convert such code to a React functional signature where the Line is simply part of the JSX composite object that I return from my App component.

I have noticed that the following examples also answer quite a bit of my question.
https://codesandbox.io/examples/package/react-konva

I like the way the codesandbox examples are structured since they mirror how I build functional components using JSX.

Other partial examples I've found include:

- https://codesandbox.io/s/oxwx9q9ko6

However I am looking for something a bit more complete, relative to a polygon editor.

I am also wondering. Most of the react-konva examples seem to be using the older React Component methodology. I tend to use Reacts functional interface. Will react-konva work just fine if I build all of my app components (that use React Konva), as functional components? 

Thanks.

**Comment by davesargrad** [comment] 2022-12-13 16:57
This may be my answer:
https://devmuscle.com/blog/react-konva-image-annotation

**Comment by ejarzo** [comment] 2022-12-14 05:13
Hey @davesargrad this is a few years old, but I've done something similar for https://shapeyourmusic.dev/.

This web version doesn't delete points or add them in the middle but I've added those features for a Max/MSP version so it should be doable. Each shape contains an array of points which are rendered by the [`Shape`](https://github.com/ejarzo/Shape-Your-Music/blob/master/src/components/Shape/ContainerV2.jsx) class. Mouse clicks add to the array [here](https://github.com/ejarzo/Shape-Your-Music/blob/master/src/components/ShapeCanvas/Container.jsx#L213-L226). [`ShapeVertex`](https://github.com/ejarzo/Shape-Your-Music/blob/master/src/components/Shape/ShapeVertex.jsx) renders each point and deals with hover.

Sorry there's a lot of other stuff in this code but hopefully that helps!

**Comment by davesargrad** [comment] 2022-12-14 11:54
> Hey @davesargrad this is a few years old, but I've done something similar for https://shapeyourmusic.dev/.
> 
> This web version doesn't delete points or add them in the middle but I've added those features for a Max/MSP version so it should be doable. Each shape contains an array of points which are rendered by the [`Shape`](https://github.com/ejarzo/Shape-Your-Music/blob/master/src/components/Shape/ContainerV2.jsx) class. Mouse clicks add to the array [here](https://github.com/ejarzo/Shape-Your-Music/blob/master/src/components/ShapeCanvas/Container.jsx#L213-L226). [`ShapeVertex`](https://github.com/ejarzo/Shape-Your-Music/blob/master/src/components/Shape/ShapeVertex.jsx) renders each point and deals with hover.
> 
> Sorry there's a lot of other stuff in this code but hopefully that helps!

Thank You Elias. I will take a look.

**Comment by lavrton** [comment] 2022-12-17 14:50
You can build your app using functional components. It will work just fine. Closing the issue because the issue is very vague. If you have any specific questions, please ask them.

**Closed by lavrton** 2022-12-17 14:50 UTC

**Comment by ejarzo** [comment] 2022-12-27 22:39
@davesargrad just wanted to follow up on this because your question motivated me to implement Create + Delete points functionality to that site. You can try it at https://shapeyourmusic.dev/ (Using the "EDIT" tool, click on a midpoint to add, double click a point to delete).
