### ISSUE TITLE
Gaps in `onMouseMove` on a Layer

### ISSUE THREAD

**Issue by judehunter** [konvajs/react-konva#590] opened 2021-05-30 19:21 UTC
It seems that if you put a `onMouseMove` (or attach an event listener using a ref), once in a while there are gaps (~1s) between the event listener calls. It works well for a moment, and then stops invoking the listener for a while, just to go back to normal again.

This doesn't happen when the event listener is placed directly on `Stage`.

**Comment by lavrton** [comment] 2021-05-30 19:22
Can you make a demo?

**Comment by DarkBitz** [comment] 2021-06-22 12:07
@judehunter you are right, I have the same problem. It also applies to the MouseUp event. Which does not reach the React component that it registered. 
@lavrton you can reproduce this by registering the mouse event listener on a rect in a React functional component. If you need more details, I'll try to provide them. All events that are registered on the stage are accepted without any problems.

**Comment by lavrton** [comment] 2021-06-23 06:08
I need a demo.

**Comment by DarkBitz** [comment] 2021-06-30 14:46
@lavrton So my problem was simply that the mouse was moved out of the rectangle and then released. Then the event was not applied to the rectangle. Seems to be a desired behavior.

**Comment by lavrton** [comment] 2021-06-30 15:24
@DarkBitz for you use case, you can try to use `Konva.capturePointerEventsEnabled = true`. Or `shape.setPointerCapture(stage.getPointerPosition().id);`

Closing the issue for now. If any questions or issues. Please provide a demo.

**Closed by lavrton** 2021-06-30 15:24 UTC
