### ISSUE TITLE
How to draw circular around little circle

### ISSUE THREAD

**Issue by wahidin32** [konvajs/react-konva#506] opened 2020-08-08 04:01 UTC
i need help, how to make a big circle surrounded by small circles like these [https://prnt.sc/tw2e5w]() using konva.

Thanks in advance ^^

**Comment by lavrton** [comment] 2020-08-09 02:22
Closing as duplicate of https://github.com/konvajs/konva/issues/957

**Closed by lavrton** 2020-08-09 02:22 UTC
