### ISSUE TITLE
Unable to Drag Line When Inside Polygon

### ISSUE THREAD

**Issue by sangeetha321** [konvajs/react-konva#812] opened 2024-10-09 14:08 UTC
I'm experiencing an issue with my React-Conva components. I have two components: one for drawing lines and another for polygons. The problem occurs when I draw a line first and then a polygon. If the line is inside the polygon, I'm unable to drag the line without first moving the polygon.

Steps to Reproduce:

- Draw a line using the line component.
- Draw a polygon using the polygon component, ensuring the line is inside the polygon.
- Attempt to drag the line.
- Expected Behavior: I should be able to drag the line freely, regardless of its position relative to the polygon.

```
import { Circle, Line, Rect, Text, Group } from "react-konva";
import { Circle, Line, Rect, RegularPolygon, Text, Group} from "react-konva";

```
Actual Behavior: The line cannot be dragged if it's inside the polygon. I must first move the polygon to be able to drag the line.

I am using "react-konva": "^18.2.10"

**Comment by lavrton** [comment] 2024-10-10 16:52
Closing as duplicate of https://github.com/konvajs/konva/issues/1835

**Closed by lavrton** 2024-10-10 16:52 UTC
